//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.19 at 07:01:41 PM CEST 
//


package es.caib.gdib.ws.xsd.expediente.eni.doc.contenido;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for TipoContenido complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TipoContenido"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;element name="DatosXML" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
 *           &lt;element name="ValorBinario" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/&gt;
 *           &lt;element name="referenciaFichero" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="NombreFormato" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Id" type="{http://www.w3.org/2001/XMLSchema}ID" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TipoContenido", propOrder = {
    "datosXML",
    "valorBinario",
    "referenciaFichero",
    "nombreFormato"
})
public class TipoContenido {

    @XmlElement(name = "DatosXML")
    protected Object datosXML;
    @XmlElement(name = "ValorBinario")
    protected byte[] valorBinario;
    protected String referenciaFichero;
    @XmlElement(name = "NombreFormato", required = true)
    protected String nombreFormato;
    @XmlAttribute(name = "Id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the datosXML property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getDatosXML() {
        return datosXML;
    }

    /**
     * Sets the value of the datosXML property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setDatosXML(Object value) {
        this.datosXML = value;
    }

    /**
     * Gets the value of the valorBinario property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getValorBinario() {
        return valorBinario;
    }

    /**
     * Sets the value of the valorBinario property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setValorBinario(byte[] value) {
        this.valorBinario = value;
    }

    /**
     * Gets the value of the referenciaFichero property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferenciaFichero() {
        return referenciaFichero;
    }

    /**
     * Sets the value of the referenciaFichero property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferenciaFichero(String value) {
        this.referenciaFichero = value;
    }

    /**
     * Gets the value of the nombreFormato property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreFormato() {
        return nombreFormato;
    }

    /**
     * Sets the value of the nombreFormato property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreFormato(String value) {
        this.nombreFormato = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
