//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.19 at 07:01:41 PM CEST 
//


package es.caib.gdib.ws.xsd.expediente.eni;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import es.caib.gdib.ws.xsd.expediente.eni.doc.contenido.TipoContenido;
import es.caib.gdib.ws.xsd.expediente.eni.indice.TipoIndice;
import es.caib.gdib.ws.xsd.expediente.eni.indice.metadatos.TipoMetadatos;


/**
 * Para el intercambio de un expediente electronico, se envia en primer lugar, el indice del expediente. Posteriormente, se enviaran los documentos que lo componen , uno a uno,  y siguiendo la distribucion reflejada en el contenido del indice.
 * 
 * <p>Java class for TipoExpediente complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TipoExpediente"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://administracionelectronica.gob.es/ENI/XSD/v1.0/expediente-e/indice-e}indice"/&gt;
 *         &lt;element ref="{http://administracionelectronica.gob.es/ENI/XSD/v1.0/expediente-e/metadatos}metadatosExp"/&gt;
 *         &lt;element name="VisualizacionIndice" type="{http://administracionelectronica.gob.es/ENI/XSD/v1.0/documento-e/contenido}TipoContenido" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Id" type="{http://www.w3.org/2001/XMLSchema}ID" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TipoExpediente", propOrder = {
    "indice",
    "metadatosExp",
    "visualizacionIndice"
})
public class TipoExpediente {

    @XmlElement(namespace = "http://administracionelectronica.gob.es/ENI/XSD/v1.0/expediente-e/indice-e", required = true)
    protected TipoIndice indice;
    @XmlElement(namespace = "http://administracionelectronica.gob.es/ENI/XSD/v1.0/expediente-e/metadatos", required = true)
    protected TipoMetadatos metadatosExp;
    @XmlElement(name = "VisualizacionIndice")
    protected TipoContenido visualizacionIndice;
    @XmlAttribute(name = "Id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the indice property.
     * 
     * @return
     *     possible object is
     *     {@link TipoIndice }
     *     
     */
    public TipoIndice getIndice() {
        return indice;
    }

    /**
     * Sets the value of the indice property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoIndice }
     *     
     */
    public void setIndice(TipoIndice value) {
        this.indice = value;
    }

    /**
     * Gets the value of the metadatosExp property.
     * 
     * @return
     *     possible object is
     *     {@link TipoMetadatos }
     *     
     */
    public TipoMetadatos getMetadatosExp() {
        return metadatosExp;
    }

    /**
     * Sets the value of the metadatosExp property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoMetadatos }
     *     
     */
    public void setMetadatosExp(TipoMetadatos value) {
        this.metadatosExp = value;
    }

    /**
     * Gets the value of the visualizacionIndice property.
     * 
     * @return
     *     possible object is
     *     {@link TipoContenido }
     *     
     */
    public TipoContenido getVisualizacionIndice() {
        return visualizacionIndice;
    }

    /**
     * Sets the value of the visualizacionIndice property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoContenido }
     *     
     */
    public void setVisualizacionIndice(TipoContenido value) {
        this.visualizacionIndice = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
