//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.19 at 07:01:41 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://administracionelectronica.gob.es/ENI/XSD/v1.0/expediente-e/metadatos", 
	elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
	xmlns = {
        @javax.xml.bind.annotation.XmlNs(prefix = "eniexpmeta",
        namespaceURI="http://administracionelectronica.gob.es/ENI/XSD/v1.0/expediente-e/metadatos")
	})
package es.caib.gdib.ws.xsd.expediente.eni.indice.metadatos; 