CREATE TABLE www_gdibmem.UPGRADE_SIGNATURE_JOB(
DOCUMENT_ID VARCHAR2(50) NOT NULL,
ID_MIN_CUSTODY_SIGNATURE NUMBER(2) NOT NULL,
ID_ENI_SIGNATURE NUMBER(2) NOT NULL,
IMPLICIT_SIGNATURE NUMBER(1) NOT NULL,
TRY NUMBER(2) DEFAULT 0,
ERROR VARCHAR2(500));

CREATE TABLE www_gdibmem.CLOSE_FILE_JOB(
FILE_ID VARCHAR2(50) NOT NULL,
CLOSE_DATE DATE NOT NULL,
TRY NUMBER(2) DEFAULT 0,
ERROR VARCHAR2(500));


COMMIT;