//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.14 at 05:06:23 PM CEST 
//


package es.caib.gdib.ws.xsd.expediente.indice;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the es.caib.gdib.ws.xsd.expediente.indice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _IndiceElectronico_QNAME = new QName("urn:es:caib:archivodigital:gestiondocumental:expediente-e:indice-e:1.0", "IndiceElectronico");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: es.caib.gdib.ws.xsd.expediente.indice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TipoIndiceElectronico }
     * 
     */
    public TipoIndiceElectronico createTipoIndiceElectronico() {
        return new TipoIndiceElectronico();
    }

    /**
     * Create an instance of {@link TipoContenidoDocsReferenciados }
     * 
     */
    public TipoContenidoDocsReferenciados createTipoContenidoDocsReferenciados() {
        return new TipoContenidoDocsReferenciados();
    }

    /**
     * Create an instance of {@link TipoContenidoDocsIndizados }
     * 
     */
    public TipoContenidoDocsIndizados createTipoContenidoDocsIndizados() {
        return new TipoContenidoDocsIndizados();
    }

    /**
     * Create an instance of {@link TipoFirmaElectronica }
     * 
     */
    public TipoFirmaElectronica createTipoFirmaElectronica() {
        return new TipoFirmaElectronica();
    }

    /**
     * Create an instance of {@link TipoContenidoCarpetaIndizada }
     * 
     */
    public TipoContenidoCarpetaIndizada createTipoContenidoCarpetaIndizada() {
        return new TipoContenidoCarpetaIndizada();
    }

    /**
     * Create an instance of {@link TipoContenidoDocIndizado }
     * 
     */
    public TipoContenidoDocIndizado createTipoContenidoDocIndizado() {
        return new TipoContenidoDocIndizado();
    }

    /**
     * Create an instance of {@link TipoContenidoCarpetas }
     * 
     */
    public TipoContenidoCarpetas createTipoContenidoCarpetas() {
        return new TipoContenidoCarpetas();
    }

    /**
     * Create an instance of {@link TipoMetadatosExpediente }
     * 
     */
    public TipoMetadatosExpediente createTipoMetadatosExpediente() {
        return new TipoMetadatosExpediente();
    }

    /**
     * Create an instance of {@link TipoExpediente }
     * 
     */
    public TipoExpediente createTipoExpediente() {
        return new TipoExpediente();
    }

    /**
     * Create an instance of {@link TipoContenidoExpedientes }
     * 
     */
    public TipoContenidoExpedientes createTipoContenidoExpedientes() {
        return new TipoContenidoExpedientes();
    }

    /**
     * Create an instance of {@link TipoContenidoDocReferenciado }
     * 
     */
    public TipoContenidoDocReferenciado createTipoContenidoDocReferenciado() {
        return new TipoContenidoDocReferenciado();
    }

    /**
     * Create an instance of {@link TipoContenidoFirma }
     * 
     */
    public TipoContenidoFirma createTipoContenidoFirma() {
        return new TipoContenidoFirma();
    }

    /**
     * Create an instance of {@link TipoExpedienteReferenciado }
     * 
     */
    public TipoExpedienteReferenciado createTipoExpedienteReferenciado() {
        return new TipoExpedienteReferenciado();
    }

    /**
     * Create an instance of {@link TipoContenidoExpediente }
     * 
     */
    public TipoContenidoExpediente createTipoContenidoExpediente() {
        return new TipoContenidoExpediente();
    }

    /**
     * Create an instance of {@link TipoContenidoExpReferenciados }
     * 
     */
    public TipoContenidoExpReferenciados createTipoContenidoExpReferenciados() {
        return new TipoContenidoExpReferenciados();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipoIndiceElectronico }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:es:caib:archivodigital:gestiondocumental:expediente-e:indice-e:1.0", name = "IndiceElectronico")
    public JAXBElement<TipoIndiceElectronico> createIndiceElectronico(TipoIndiceElectronico value) {
        return new JAXBElement<TipoIndiceElectronico>(_IndiceElectronico_QNAME, TipoIndiceElectronico.class, null, value);
    }

}
