//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.14 at 05:06:23 PM CEST 
//


package es.caib.gdib.ws.xsd.expediente.indice;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Lista de documentos de un expediente o agrupación documental.
 * 
 * <p>Java class for TipoContenidoDocsIndizados complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TipoContenidoDocsIndizados">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="docIndizado" type="{urn:es:caib:archivodigital:gestiondocumental:expediente-e:indice-e:1.0}TipoContenidoDocIndizado" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TipoContenidoDocsIndizados", propOrder = {
    "docIndizado"
})
public class TipoContenidoDocsIndizados {

    @XmlElement(required = true)
    protected List<TipoContenidoDocIndizado> docIndizado;

    /**
     * Gets the value of the docIndizado property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the docIndizado property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocIndizado().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TipoContenidoDocIndizado }
     * 
     * 
     */
    public List<TipoContenidoDocIndizado> getDocIndizado() {
        if (docIndizado == null) {
            docIndizado = new ArrayList<TipoContenidoDocIndizado>();
        }
        return this.docIndizado;
    }

}
