//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.14 at 05:06:23 PM CEST 
//


package es.caib.gdib.ws.xsd.expediente.indice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Define la información de la firma electrónica que garantiza la integridad del índice electrónico.
 * 
 * <p>Java class for TipoFirmaElectronica complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TipoFirmaElectronica">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tipoFirma" type="{urn:es:caib:archivodigital:gestiondocumental:expediente-e:indice-e:1.0}TipoFormatoFirma"/>
 *         &lt;element name="contenidoFirma" type="{urn:es:caib:archivodigital:gestiondocumental:expediente-e:indice-e:1.0}TipoContenidoFirma"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TipoFirmaElectronica", propOrder = {
    "tipoFirma",
    "contenidoFirma"
})
public class TipoFirmaElectronica {

    @XmlElement(required = true, defaultValue = "TF01")
    protected TipoFormatoFirma tipoFirma;
    @XmlElement(required = true)
    protected TipoContenidoFirma contenidoFirma;

    /**
     * Gets the value of the tipoFirma property.
     * 
     * @return
     *     possible object is
     *     {@link TipoFormatoFirma }
     *     
     */
    public TipoFormatoFirma getTipoFirma() {
        return tipoFirma;
    }

    /**
     * Sets the value of the tipoFirma property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoFormatoFirma }
     *     
     */
    public void setTipoFirma(TipoFormatoFirma value) {
        this.tipoFirma = value;
    }

    /**
     * Gets the value of the contenidoFirma property.
     * 
     * @return
     *     possible object is
     *     {@link TipoContenidoFirma }
     *     
     */
    public TipoContenidoFirma getContenidoFirma() {
        return contenidoFirma;
    }

    /**
     * Sets the value of the contenidoFirma property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoContenidoFirma }
     *     
     */
    public void setContenidoFirma(TipoContenidoFirma value) {
        this.contenidoFirma = value;
    }

}
