//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.14 at 05:06:23 PM CEST 
//


package es.caib.gdib.ws.xsd.expediente.indice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Define el contenido de un documento simple incluido en el índice de un expediente.
 * 
 * <p>Java class for TipoContenidoDocIndizado complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TipoContenidoDocIndizado">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nombre" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="hash" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="funcionHash" type="{urn:es:caib:archivodigital:gestiondocumental:expediente-e:indice-e:1.0}TipoFuncionHash"/>
 *         &lt;element name="fechaIncorporacion" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="ordenDocumento" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TipoContenidoDocIndizado", propOrder = {
    "nombre",
    "hash",
    "funcionHash",
    "fechaIncorporacion",
    "ordenDocumento"
})
public class TipoContenidoDocIndizado {

    @XmlElement(required = true)
    protected String nombre;
    @XmlElement(required = true)
    protected String hash;
    @XmlElement(required = true)
    protected TipoFuncionHash funcionHash;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar fechaIncorporacion;
    protected int ordenDocumento;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the nombre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * Sets the value of the nombre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombre(String value) {
        this.nombre = value;
    }

    /**
     * Gets the value of the hash property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHash() {
        return hash;
    }

    /**
     * Sets the value of the hash property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHash(String value) {
        this.hash = value;
    }

    /**
     * Gets the value of the funcionHash property.
     * 
     * @return
     *     possible object is
     *     {@link TipoFuncionHash }
     *     
     */
    public TipoFuncionHash getFuncionHash() {
        return funcionHash;
    }

    /**
     * Sets the value of the funcionHash property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoFuncionHash }
     *     
     */
    public void setFuncionHash(TipoFuncionHash value) {
        this.funcionHash = value;
    }

    /**
     * Gets the value of the fechaIncorporacion property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaIncorporacion() {
        return fechaIncorporacion;
    }

    /**
     * Sets the value of the fechaIncorporacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaIncorporacion(XMLGregorianCalendar value) {
        this.fechaIncorporacion = value;
    }

    /**
     * Gets the value of the ordenDocumento property.
     * 
     */
    public int getOrdenDocumento() {
        return ordenDocumento;
    }

    /**
     * Sets the value of the ordenDocumento property.
     * 
     */
    public void setOrdenDocumento(int value) {
        this.ordenDocumento = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
