//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.14 at 05:06:23 PM CEST 
//


package es.caib.gdib.ws.xsd.expediente.indice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Define el contenido del expediente que será incluido en el índice. Inicialmente, los elementos que pueden formar parte de un expediente son: documentos simples, agrupaciones documentales, sub expedientes, y documentos y expedientes asociados o referenciados.
 * 
 * <p>Java class for TipoContenidoExpediente complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TipoContenidoExpediente">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="documentosIndizados" type="{urn:es:caib:archivodigital:gestiondocumental:expediente-e:indice-e:1.0}TipoContenidoDocsIndizados" minOccurs="0"/>
 *         &lt;element name="documentosReferenciados" type="{urn:es:caib:archivodigital:gestiondocumental:expediente-e:indice-e:1.0}TipoContenidoDocsReferenciados" minOccurs="0"/>
 *         &lt;element name="subexpedientesIndizados" type="{urn:es:caib:archivodigital:gestiondocumental:expediente-e:indice-e:1.0}TipoContenidoExpedientes" minOccurs="0"/>
 *         &lt;element name="expedientesReferenciados" type="{urn:es:caib:archivodigital:gestiondocumental:expediente-e:indice-e:1.0}TipoContenidoExpReferenciados" minOccurs="0"/>
 *         &lt;element name="carpetasIndizadas" type="{urn:es:caib:archivodigital:gestiondocumental:expediente-e:indice-e:1.0}TipoContenidoCarpetas" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TipoContenidoExpediente", propOrder = {
    "documentosIndizados",
    "documentosReferenciados",
    "subexpedientesIndizados",
    "expedientesReferenciados",
    "carpetasIndizadas"
})
public class TipoContenidoExpediente {

    protected TipoContenidoDocsIndizados documentosIndizados;
    protected TipoContenidoDocsReferenciados documentosReferenciados;
    protected TipoContenidoExpedientes subexpedientesIndizados;
    protected TipoContenidoExpReferenciados expedientesReferenciados;
    protected TipoContenidoCarpetas carpetasIndizadas;

    /**
     * Gets the value of the documentosIndizados property.
     * 
     * @return
     *     possible object is
     *     {@link TipoContenidoDocsIndizados }
     *     
     */
    public TipoContenidoDocsIndizados getDocumentosIndizados() {
        return documentosIndizados;
    }

    /**
     * Sets the value of the documentosIndizados property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoContenidoDocsIndizados }
     *     
     */
    public void setDocumentosIndizados(TipoContenidoDocsIndizados value) {
        this.documentosIndizados = value;
    }

    /**
     * Gets the value of the documentosReferenciados property.
     * 
     * @return
     *     possible object is
     *     {@link TipoContenidoDocsReferenciados }
     *     
     */
    public TipoContenidoDocsReferenciados getDocumentosReferenciados() {
        return documentosReferenciados;
    }

    /**
     * Sets the value of the documentosReferenciados property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoContenidoDocsReferenciados }
     *     
     */
    public void setDocumentosReferenciados(TipoContenidoDocsReferenciados value) {
        this.documentosReferenciados = value;
    }

    /**
     * Gets the value of the subexpedientesIndizados property.
     * 
     * @return
     *     possible object is
     *     {@link TipoContenidoExpedientes }
     *     
     */
    public TipoContenidoExpedientes getSubexpedientesIndizados() {
        return subexpedientesIndizados;
    }

    /**
     * Sets the value of the subexpedientesIndizados property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoContenidoExpedientes }
     *     
     */
    public void setSubexpedientesIndizados(TipoContenidoExpedientes value) {
        this.subexpedientesIndizados = value;
    }

    /**
     * Gets the value of the expedientesReferenciados property.
     * 
     * @return
     *     possible object is
     *     {@link TipoContenidoExpReferenciados }
     *     
     */
    public TipoContenidoExpReferenciados getExpedientesReferenciados() {
        return expedientesReferenciados;
    }

    /**
     * Sets the value of the expedientesReferenciados property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoContenidoExpReferenciados }
     *     
     */
    public void setExpedientesReferenciados(TipoContenidoExpReferenciados value) {
        this.expedientesReferenciados = value;
    }

    /**
     * Gets the value of the carpetasIndizadas property.
     * 
     * @return
     *     possible object is
     *     {@link TipoContenidoCarpetas }
     *     
     */
    public TipoContenidoCarpetas getCarpetasIndizadas() {
        return carpetasIndizadas;
    }

    /**
     * Sets the value of the carpetasIndizadas property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoContenidoCarpetas }
     *     
     */
    public void setCarpetasIndizadas(TipoContenidoCarpetas value) {
        this.carpetasIndizadas = value;
    }

}
