
-- desde usuario GDIB

CREATE TABLE GDIB.CERTIFICATES (
  SERIALNUMBER VARCHAR2(50) NOT NULL,
  SUBJECTDN VARCHAR2(250 CHAR) NOT NULL,
  ISSUERDN VARCHAR2(250 CHAR) NOT NULL,
  NOTBEFORE DATE NOT NULL,
  NOTAFTER DATE NOT NULL,
  NUMINDICES NUMBER(20,0) NOT NULL,  -- indica el numero de indices que existen con este certificado
  CONSTRAINT GDIBCERTIFICATES_PK PRIMARY KEY (SERIALNUMBER)
)

GRANT SELECT, INSERT, UPDATE, DELETE ON CERTIFICATES TO WWW_GDIB;


-- desde usuario WWW_GDIB

create synonym CERTIFICATES FOR GDIB.CERTIFICATES;


